name: My First GitHub Actions
#raju
on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v3

      - name: Select Python manually
        run: |
          echo "Using Python ${{ matrix.python-version }}"
          if [ "${{ matrix.python-version }}" = "3.8" ]; then
            PYBIN="python3.8"
          else
            PYBIN="python3.9"
          fi
          echo "PYBIN=$PYBIN" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          $PYBIN -m pip install --upgrade pip
          $PYBIN -m pip install pytest

      - name: Run tests
        run: |
          cd src
          $PYBIN -m pytest addition.py
