name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3

    - name: Select Python version manually
      id: set-python
      run: |
        if [ "${{ matrix.python-version }}" = "3.8" ]; then
          echo "PYBIN=/usr/local/bin/python3.8" >> $GITHUB_ENV
        elif [ "${{ matrix.python-version }}" = "3.9" ]; then
          echo "PYBIN=/usr/local/bin/python3.9" >> $GITHUB_ENV
        fi

    - name: Install dependencies
      run: |
        $PYBIN -m pip install --upgrade pip
        $PYBIN -m pip install pytest

    - name: Run tests
      run: |
        cd src
        $PYBIN -m pytest addition.py
